---
env:
  global:
  - JRUBY_OPTS="-Xcli.debug=true --debug"
  - CC_TEST_REPORTER_ID=3ed1c79841ccc5d053b995c63c0ead562427a77dba728601b8d19f02b16ac0f2

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- bundle exec rake

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_install:
- gem update --system
- gem install bundler -v 1.16.5

install:
- bundle install

bundler_args: --no-deployment --jobs 3 --retry 3

language: ruby
cache: bundler
rvm:
- 2.3.7
- 2.4.4
- 2.5.1
